// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: drops.sql

package db

import (
	"context"
	"database/sql"
)

const createDrop = `-- name: CreateDrop :one
INSERT INTO drops (
    user_id,
    topic,
    url,
    user_notes,
    priority
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, topic, url, user_notes, added_date, updated_at, status, last_sent_date, send_count, priority
`

type CreateDropParams struct {
	UserID    sql.NullString
	Topic     string
	Url       string
	UserNotes sql.NullString
	Priority  sql.NullInt32
}

func (q *Queries) CreateDrop(ctx context.Context, arg CreateDropParams) (Drop, error) {
	row := q.db.QueryRowContext(ctx, createDrop,
		arg.UserID,
		arg.Topic,
		arg.Url,
		arg.UserNotes,
		arg.Priority,
	)
	var i Drop
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Topic,
		&i.Url,
		&i.UserNotes,
		&i.AddedDate,
		&i.UpdatedAt,
		&i.Status,
		&i.LastSentDate,
		&i.SendCount,
		&i.Priority,
	)
	return i, err
}
