// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Drop struct {
	ID           uuid.UUID
	UserID       sql.NullString
	Topic        string
	Url          string
	UserNotes    sql.NullString
	AddedDate    time.Time
	UpdatedAt    time.Time
	Status       string
	LastSentDate sql.NullTime
	SendCount    int32
	Priority     sql.NullInt32
}

type DropsItemTag struct {
	DropsID uuid.UUID
	TagID   int32
}

type Tag struct {
	ID   int32
	Name string
}
